# Generated by Django 5.2.1 on 2025-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totpdevice',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
